[package]
name = "skim-navi"
version = "0.1.10"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "ğŸ› A friendlier skim faÃ§ade."
categories = [
    "command-line-utilities",
]
keywords = [
    "cli",
]
repository = "https://github.com/mihaigalos/skim-navi"
license = "MIT"

[dependencies]
log = "0.4.21"
skim = "0.10.4"

[dev-dependencies]
regex = "1.7.1"
reqwest = "0.11.14"
tokio = { version = "1.27.0", features = ["full"] }
warpy = "0.3.5"
