[package]
name = "skim-navi"
version = "0.1.1"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "ğŸ› A friendlier skim faÃ§ade."
categories = [
    "command-line-utilities",
]
keywords = [
    "cli",
]
repository = "https://github.com/mihaigalos/skim-navi"
license = "MIT"

[dependencies]
log = "0.4.17"
skim = "0.10.2"