[package]
name = "skim-navi"
version = "0.0.3"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "ğŸ› A friendlier skim faÃ§ade."
categories = [
    "command-line-utilities",
]
keywords = [
    "cli",
]
repository = "https://github.com/mihaigalos/skim-navi"
license = "MIT"

[dependencies]
skim = "0.9.4"
