[package]
name = "skim-navi"
version = "0.1.3"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "ğŸ› A friendlier skim faÃ§ade."
categories = [
    "command-line-utilities",
]
keywords = [
    "cli",
]
repository = "https://github.com/mihaigalos/skim-navi"
license = "MIT"

[dependencies]
log = "0.4.17"
skim = "0.10.2"

[dev-dependencies]
regex = "1.7.1"
reqwest = "0.11.13"
tokio = { version = "1.24.2", features = ["full"] }
warpy = "0.3.3"
